[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "monkeys"
version = "0.1.0"
dependencies = ["numpy", "pandas", "scikit-learn"]

[tool.setuptools.packages.find]
include = ["monkeys*"]
exclude = ["experiments*"]
